Repository AgOpenGPS-Official/AgOpenGPS, pull requests merged in 2025-01, with the labels that each got.

#508 bugfix_images
  SourceCode/GPS/Forms/Settings/FormConfig.Designer.cs
Labels: bug

#511 Remove unused code
  SourceCode/AgIO/Source/Classes/CGLM.cs
  SourceCode/GPS/Classes/vec3.cs
Labels: refactoring

#513 Refactored Sections.Designer.cs
  SourceCode/GPS/Forms/FormGPS.Designer.cs
  SourceCode/GPS/Forms/OpenGL.Designer.cs
  SourceCode/GPS/Forms/Sections.Designer.cs
Labels: refactoring

#569 change label names to logical names instead of labelXX for config design
  SourceCode/GPS/Culture/gStr.Designer.cs
  SourceCode/GPS/Culture/gStr.nl.resx
  SourceCode/GPS/Culture/gStr.resx
  SourceCode/GPS/Culture/gStr.zh-CHS.resx
  SourceCode/GPS/Forms/Settings/ConfigData.Designer.cs
  SourceCode/GPS/Forms/Settings/ConfigMenu.Designer.cs
  SourceCode/GPS/Forms/Settings/ConfigTool.Designer.cs
  SourceCode/GPS/Forms/Settings/ConfigVehicle.Designer.cs
  SourceCode/GPS/Forms/Settings/FormConfig.Designer.cs
  SourceCode/GPS/Forms/Settings/FormConfig.cs
Labels: enhancement

#591 fix exception if 2 points made and slicer was ticked gave a exception
  SourceCode/GPS/Forms/Field/FormBndTool.cs
Labels: bug

#586 FormFirst Translation resx lines and labels
  SourceCode/AgIO/Source/Properties/Settings.Designer.cs
  SourceCode/GPS/Culture/gStr.Designer.cs
  SourceCode/GPS/Culture/gStr.nl.resx
  SourceCode/GPS/Culture/gStr.resx
  SourceCode/GPS/Forms/Form_First.Designer.cs
  SourceCode/GPS/Forms/Form_First.cs
  SourceCode/GPS/Forms/Form_First.resx
  SourceCode/GPS/Forms/Settings/FormConfig.cs
  SourceCode/GPS/Properties/Settings.Designer.cs
Labels: enhancement

#601 more translation options for flag,fieldata,fielddir
  SourceCode/GPS/Culture/gStr.Designer.cs
  SourceCode/GPS/Culture/gStr.nl.resx
  SourceCode/GPS/Culture/gStr.resx
  SourceCode/GPS/Forms/Field/FormBndTool.Designer.cs
  SourceCode/GPS/Forms/Field/FormBndTool.cs
  SourceCode/GPS/Forms/Field/FormEnterFlag.Designer.cs
  SourceCode/GPS/Forms/Field/FormEnterFlag.cs
  SourceCode/GPS/Forms/Field/FormFieldData.Designer.cs
  SourceCode/GPS/Forms/Field/FormFieldData.cs
  SourceCode/GPS/Forms/Field/FormFieldDir.Designer.cs
  SourceCode/GPS/Forms/Field/FormFieldDir.cs
Labels: enhancement

#604 translations done for all fieldforms
  SourceCode/GPS/Culture/gStr.Designer.cs
  SourceCode/GPS/Culture/gStr.nl.resx
  SourceCode/GPS/Culture/gStr.resx
  SourceCode/GPS/Forms/Field/FormFieldISOXML.Designer.cs
  SourceCode/GPS/Forms/Field/FormFieldISOXML.cs
  SourceCode/GPS/Forms/Field/FormFieldKML.Designer.cs
  SourceCode/GPS/Forms/Field/FormFieldKML.cs
  SourceCode/GPS/Forms/Field/FormFlags.Designer.cs
  SourceCode/GPS/Forms/Field/FormFlags.cs
  SourceCode/GPS/Forms/Field/FormMap.Designer.cs
  SourceCode/GPS/Forms/Field/FormMap.cs
  SourceCode/GPS/Forms/Field/FormSaveOrNot.Designer.cs
  SourceCode/GPS/Forms/Field/FormSaveOrNot.cs
Labels: enhancement
